---
- name: Ensure network config directory exists
  file: path=/etc/network/interfaces.d state=directory mode=0755

- name: Drop network config in place
  template: src=openstack.j2 dest=/etc/network/interfaces.d/openstack.cfg owner=root group=root mode=0644

- name: Edit Networking
  shell: /vagrant/networking.sh
